CREATE DATABASE IF NOT EXISTS hrsystem2;
USE hrsystem2;
CREATE TABLE IF NOT EXISTS CustomUser (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    userRole ENUM('ADMIN', 'USER', 'REQRUITER') NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);