CREATE DATABASE IF NOT EXISTS hrsystem;
USE hrsystem;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    userRole ENUM('ADMIN', 'USER', 'REQRUITER') NOT NULL,
    profile_image VARCHAR(512),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE users
ADD COLUMN department VARCHAR(255) AFTER userRole;

ALTER TABLE users MODIFY userRole VARCHAR(50) NOT NULL;

CREATE TABLE payroll (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  month_year VARCHAR(7) NOT NULL, -- e.g., '2025-04'
  base_salary DECIMAL(10, 2) NOT NULL,
  bonus DECIMAL(10, 2) DEFAULT 0,
  deduction DECIMAL(10, 2) DEFAULT 0,
  net_pay DECIMAL(10, 2) GENERATED ALWAYS AS (base_salary + bonus - deduction) STORED,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


