CREATE DATABASE IF NOT EXISTS hrsystem;
USE hrsystem;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    userRole ENUM('ADMIN', 'USER', 'REQRUITER') NOT NULL,
    profile_image VARCHAR(512),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE users
ADD COLUMN department VARCHAR(255) AFTER userRole;

ALTER TABLE users MODIFY userRole VARCHAR(50) NOT NULL;

